### ISSUE TITLE
モジュールのコンストラクタに独自の処理を含めて良いか？

### ISSUE THREAD

**Issue by syoch** [Mine-Code/discord-bot#2]
モジュールのコンストラクタに独自の処理を含めた場合の実行タイミング、副作用や気をつける点などについて知りたい。

**Comment by yukikamome316** [comment]
コンストラクタはBot起動時に即時呼ばれる。基本的にメンバ変数などの初期化処理はコンストラクタ内で行ってほしい。
BotModuleクラスを継承して、基本的にはinit関数を新たに作成することにしている(SystemControllerモジュールを参照してほしい)んだけど、これは主にイベントハンドラの登録に使う方針だよ。
副作用については思いつかないから大丈夫だと思う。

**Comment by syoch** [comment]
変数の初期化とかリソースの確保はコンストラクタで
クラス自体の初期化処理は init() でよさそうな感じかな
ありがとう
